baseURL = 'https://heatherjones.netlify.app/'
languageCode = 'en-us'
title = 'Heather Jones'

[[menus.main]]
name = 'Paintings'
pageRef = '/paintings'
weight = 40

[[menus.main]]
name = 'Collections'
pageRef = '/collections'
weight = 50

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 60

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"

[taxonomies]
  collection = 'collections'
  category = 'categories'
  tag = 'tags'