baseURL = 'https://heatherjones.netlify.app/'
languageCode = 'en-us'
title = 'Heather Jones'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'All Paintings'
pageRef = '/paintings'
weight = 40

[[menus.main]]
name = 'Browse by Collection'
pageRef = '/collections'
weight = 50

[[menus.main]]
name = 'About Heather'
pageRef = '/about'
weight = 60

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"

[taxonomies]
  collection = 'collections'
  category = 'categories'
  tag = 'tags'