baseURL = 'https://heatherheiskelljones.netlify.app/'
languageCode = 'en-us'
title = 'Heather Jones'

[params]
  subtitle = 'Fine Art'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Collections'
pageRef = '/collections'
weight = 20

[[menus.main]]
name = 'About Heather'
pageRef = '/about'
weight = 60

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"

[taxonomies]
  collections = 'collections'
  category = 'categories'
  tag = 'tags'