baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Paintings'
pageRef = '/paintings'
weight = 40

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 60

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"
