baseURL = 'https://heatherheiskelljones.netlify.app/'
languageCode = 'en-us'
title = 'Heather Heiskell Jones'
theme = 'hhjpaintings'
timeout = '120s'

[taxonomies]
  collection = 'collections'
  category = 'categories'
  tag = 'tags'

[caches]
  [caches.images]
    dir = ':cacheDir/:project'
    maxAge = "800h"