baseURL = 'https://heatherjones.netlify.app/'
languageCode = 'en-us'
title = 'Heather Heiskell Jones | Fine Art'
theme = 'hhjpaintings'

[taxonomies]
  collection = 'collections'
  category = 'categories'
  tag = 'tags'