baseURL = 'https://heatherheiskelljones.netlify.app/'
languageCode = 'en-us'
title = 'Heather Heiskell Jones'
theme = 'hhjpaintings'
timeout = '60s'

[taxonomies]
  collection = 'collections'
  category = 'categories'
  tag = 'tags'