backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: assets/img
public_folder: /img
publish_mode: editorial_workflow
collections:
  - label: "Pages"
    name: "sitePages"
    create: false
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "data/homepage.yml"
        editor:
          preview: false
        fields:
          - label: "Hero"
            name: "hero"
            widget: object
            fields:
              - { label: "Heading", name: 'heading', widget: 'string' }
              - { label: "Lede", name: 'lede', widget: 'text', required: false }
              - label: "Call to Action"
                name: "cta"
                widget: list
                required: false
                fields:
                  - { label: "Button Text", name: "button_text", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
      - label: 'About'
        name: 'about'
        file: "data/about.yml"
        editor:
          preview: false
        fields:
          - { label: 'Heading', name: 'heading', widget: 'string' }
          - { label: 'Featured Image', name: 'featured_image', widget: 'image', required: false }
          - { label: 'Featured Image Alt Text', name: 'featured_image_alt', widget: 'string', required: false }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'paintings'
    label: 'Paintings'
    folder: "content/paintings"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    sortable_fields: ['date', 'title']
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Show', name: 'published', widget: 'boolean', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'featured_image', widget: 'image' }
      - { label: 'Image Alt Text', name: 'featured_image_alt', widget: 'text', required: false }
      - { label: 'Collections', name: 'collections', widget: 'list', hint: "These should be consistent with other paintings of the same collection and are case-sensitive. Use all lowercase letters, hyphens instead of spaces, and no special characters other than hyphens." }
      - { label: 'Medium', name: 'medium', widget: 'text', required: false }
      - { label: 'Framing', name: 'framing', widget: 'text', required: false }
      - { label: 'Height (inches)', name: 'height', widget: number, required: false }
      - { label: 'Width (inches)', name: 'width', widget: number, required: false }
      - { label: 'Description', name: 'description', widget: 'text', required: false }
      - { label: 'Private Collection', name: 'private', widget: 'boolean', default: false, required: false }
      - { label: 'Price', name: 'price', widget: 'number', value_type: 'float', step: .01 }
      - { label: 'Sold', name: 'sold', widget: 'boolean', required: false }
  - label: "Settings"
    name: "settings"
    create: false
    editor:
      preview: false
    files:
      - label: "Config"
        name: "config"
        file: "data/settings.yml"
        editor:
          preview: false
        fields:
          - { label: "Site Description", name: "description", widget: "text" }
          - { label: "Commission Message", name: "commission", widget: "markdown", required: false }
          - label: "Email"
            name: "email"
            widget: "string"
            required: false
          - label: "Social Media Accounts"
            name: "social_media_accounts"
            widget: "list"
            required: false
            fields:
              - { label: "Platform", name: "platform", widget: "string" }
              - { label: "Username", name: "username", widget: "string", required: false }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Icon Code", name: "icon_code", widget: "string", required: false }
  # - name: 'blog'
  #   label: 'Blog'
  #   folder: "content/posts"
  #   create: true
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   editor:
  #     preview: false
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  #     - { label: 'Description', name: 'description', widget: 'string' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }